In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9090, 367, 500, 1610],
 [9090, 367, 500, 3658],
 [9090, 8008, 500, 6122],
 [4741, 7199, 8117, 8142, 9400],
 [4741, 7199, 8117, 8142, 3381],
 [2895, 9090, 3096, 500, 2988],
 [8368, 5186, 4697, 8142]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9090  367  500 1610]
 [   0    0    0    0 9090  367  500 3658]
 [   0    0    0    0 9090 8008  500 6122]
 [   0    0    0 4741 7199 8117 8142 9400]
 [   0    0    0 4741 7199 8117 8142 3381]
 [   0    0    0 2895 9090 3096  500 2988]
 [   0    0    0    0 8368 5186 4697 8142]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 276ms/step


array([[[ 3.71882580e-02, -2.54002102e-02,  4.88480963e-02,
         -7.77007267e-03,  3.21920961e-03, -8.21094587e-03,
          2.33720578e-02,  3.56475972e-02,  2.65160836e-02,
          3.15964110e-02],
        [ 3.71882580e-02, -2.54002102e-02,  4.88480963e-02,
         -7.77007267e-03,  3.21920961e-03, -8.21094587e-03,
          2.33720578e-02,  3.56475972e-02,  2.65160836e-02,
          3.15964110e-02],
        [ 3.71882580e-02, -2.54002102e-02,  4.88480963e-02,
         -7.77007267e-03,  3.21920961e-03, -8.21094587e-03,
          2.33720578e-02,  3.56475972e-02,  2.65160836e-02,
          3.15964110e-02],
        [ 3.71882580e-02, -2.54002102e-02,  4.88480963e-02,
         -7.77007267e-03,  3.21920961e-03, -8.21094587e-03,
          2.33720578e-02,  3.56475972e-02,  2.65160836e-02,
          3.15964110e-02],
        [-2.25597378e-02, -4.21871059e-02,  4.90973033e-02,
          3.72996815e-02, -3.30390483e-02, -2.44254228e-02,
          4.33387272e-02, -2.39177588e-02, -2.948329

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9090,  367,  500, 1610])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 72ms/step


array([[ 0.03718826, -0.02540021,  0.0488481 , -0.00777007,  0.00321921,
        -0.00821095,  0.02337206,  0.0356476 ,  0.02651608,  0.03159641],
       [ 0.03718826, -0.02540021,  0.0488481 , -0.00777007,  0.00321921,
        -0.00821095,  0.02337206,  0.0356476 ,  0.02651608,  0.03159641],
       [ 0.03718826, -0.02540021,  0.0488481 , -0.00777007,  0.00321921,
        -0.00821095,  0.02337206,  0.0356476 ,  0.02651608,  0.03159641],
       [ 0.03718826, -0.02540021,  0.0488481 , -0.00777007,  0.00321921,
        -0.00821095,  0.02337206,  0.0356476 ,  0.02651608,  0.03159641],
       [-0.02255974, -0.04218711,  0.0490973 ,  0.03729968, -0.03303905,
        -0.02442542,  0.04333873, -0.02391776, -0.02948329, -0.01575054],
       [ 0.04247577,  0.01459273,  0.04362626,  0.03916698,  0.0144268 ,
         0.00895367, -0.02157921, -0.00748589, -0.04495734,  0.01116556],
       [-0.03462153, -0.00947364,  0.0326139 , -0.03302111,  0.01638732,
         0.02516175, -0.0284601 ,  0.03186001